### ISSUE TITLE
Is this alive?

### ISSUE THREAD

**Issue by damoodamoo** [sjwaight/Azure-Functions-Postgres-Binding#1]
...be interested in hearing if you got anywhere with this? We might be looking to use Postgres with Functions soon...

**Comment by sjwaight** [comment]
Good question. It was started off the back of a conversation and hasn't progressed. Would you be able to list a few scenarios you'd want supported in order for me to do some initial planning and scoping?

**Comment by damoodamoo** [comment]
I'm also seeing if the product team have any plans for this. I think at a base level we'd need:
* Get a row by Id
* Add / Update a row
* Maybe supporting POCO translation to a row? dunno. 

Thinking about this ourselves but need to make sure we can come up with something maintainable for a customer.

**Comment by sjwaight** [comment]
OK, so primarily basic CRUD operations against tables (as a starting point) with the ability to hydrate to/from a POCO... Let me know if you get a response from engineering on this (and who it was ;)).

Let me have a think and a play.

**Comment by damoodamoo** [comment]
Hiya - I think after hearing back from the functions team (Paul Batum) we're not going to pursue this. Feeling is that adding support for relational databases in function bindings is too complex and difficult to support. Think we'll go with a helper method instead.
